### ISSUE TITLE
Kamera mozgás

### ISSUE THREAD

**Issue by BGERGO7** [BGERGO7/SMAASH#15]

**Comment by BGERGO7** [comment]
Kamera mozgás csak az egyiknél működik!

**Comment by BGERGO7** [comment]
Camera attach a playerrel?

**Comment by BGERGO7** [comment]
https://www.youtube.com/watch?v=6khig1_Pk3E

**Comment by BDonat05** [comment]
fixed.

**Comment by BGERGO7** [comment]
Amikor a karakter fentre spawnol a platformra es leugrik, akkor a kamera nem koveti. Plusz, ha fent van a platformon a jatekos, akkor kilatszik a map szele.
